### PR TITLE
Add Github Actions Workflow for Automated Testing

### PR DESCRIPTION
**Pull request by wrharding**
I've added all currently supported OS's to Github Actions workflow's. Github Actions is [completely free](https://github.com/features/actions#pricing-details) for public repositories and could provide a more uniform test bed for PR's. It has performed similarly, if not faster than my host machine. See [wrharding/mhn/actions](https://github.com/wrharding/mhn/actions)

The Ubuntu 16.04 and CentOS 6 Workflow's are spun up via Vagrant with Virtual Box on a Mac OS 10.15 Runner. Mac OS is the only Runner that currently supports virtualization and will need to be utilized if anything besides Ubuntu >= 18.04 is to be supported by this project. See actions/virtual-environments#3287 for the unfortunate timing of Ubuntu 16.04 Runner depreciation this month.

I'm submitting this PR as a draft for consideration as I look into adding Workflows for Ubuntu 20.04 (see #778, #779, and #793), Debian 9 (#695), Debian 10 (#790), and CentOS 7 (#542 and #748). I'm hoping for a worthwhile discussion on utilizing Actions and how it can be best utilized for this project.

### CODE REVIEW

**Comment by wrharding** [comment]
The Vagrantfile has been updated to include all three supported OS's.

**Comment by wrharding** [comment]
For consideration: Github Actions

I will say that running 4 actions with notifications was a small mistake on my part so whomever is the maintainer of this repo will want them turned off. See my page for the resultant spam: https://github.com/wrharding/mhn/actions

Additionally, I've held off on adding Debian 9/10 and CentOS 7 Workflows until this PR has been reviewed. I'm more than happy to make said Workflows after an initial review.

**Comment by d1str0** [comment]
Now is fine.

**Comment by wrharding** [comment]
@d1str0, I believe this is ready for review. The one caveat is Vagrant cloud responding with a 429 if you request the same box 15-30 minutes a part.

Also noteworthy: These Workflows only test the dependencies of MHN. Without a mock config.py file there is no way to test a fully deployment. On that note though, how was CircleCI previously setup? I see it keeps failing because the configuration file no longer exists for it.

**Comment by d1str0** [comment]
We probably want to cache the vagrant box so it doesnt need to be downloaded every time. 

I dont remember exactly what circleci did, but I dont think we ever got it working fully.

**Comment by wrharding** [comment]
@d1str0 Any thoughts on this merge? Questions or concerns?

**Pull request merged**
